apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
spec:
  type: {{ .Values.Service.type}}
  selector:
    app: spam-app
  ports:
    - port: {{ .Values.Service.port}}
      protocol: TCP
      targetPort: {{ .Values.Service.port}}
      name: http