{
 "title": "Spam-App-Custom-Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Platform Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Growth by platform",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "topk(3,count by (platform) (random_gauge_1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric vary across different platform",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(15,avg by (platform) (random_gauge_1))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Overall Metrics Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Logs Growth In VM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 15 },
   "targets": [
    { "expr": "count(random_gauge_1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Logs Analysing (gauge 1)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(random_gauge_1)", "legendFormat": "__auto" }
   ]
  }
 ]
}